---BD Laborator 1--


---ex 4---
SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTAMENT;

SELECT * FROM JOBS;

SELECT * FROM JOB_HISTORY;

SELECT * FROM LOCATIONS;

SELECT * FROM COUNTRIES;

SELECT * FROM REGIONS;



---ex 5---
SELECT
    EMPLOYEE_ID "id angajat",
    concat(concat(FIRST_NAME,' '),LAST_NAME) "nume",
    JOB_ID "job id",
    to_char(HIRE_DATE,'yyyy/mm/dd') "data angajarii"
FROM EMPLOYEES;


---ex 6--

--cu duplicate
SELECT
     JOB_ID
FROM EMPLOYEES;

--fara duplicate
SELECT
    DISTINCT JOB_ID
FROM EMPLOYEES;


--ex 7
SELECT
    FIRST_NAME || ', '|| JOB_ID "Angajat si titlu"
FROM EMPLOYEES;


--ex 8
SELECT
    LAST_NAME "nume",
    SALARY || '$' "salAriu"
FROM EMPLOYEES
WHERE SALARY>=2850;


--ex 9
SELECT
    FIRST_NAME || LAST_NAME "nume",
    SALARY "salariu"
FROM EMPLOYEES
WHERE EMPLOYEE_ID=104;


--ex 10
SELECT
    LAST_NAME "nume",
    SALARY || '$' "salAriu"
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 1500 AND 2850;

--ex 11
SELECT
    FIRST_NAME,
    JOB_ID,
    HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '20-feb-1987' AND '01-may-1989'
order by HIRE_DATE;
--operatorul BETWEEN val1 AND val =>interval inchis

--ex 12
SELECT
    LAST_NAME || FIRST_NAME "nume",
    DEPARTMENT_ID "departament"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,30)
ORDER BY LAST_NAME
--operatorul IN () =>multime

--ex 13
SELECT
    FIRST_NAME ||' '|| LAST_NAME "Angajat",
    SALARY "Salariu lunar",
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY>=1500 AND (DEPARTMENT_ID=10 OR DEPARTMENT_ID=30);

--ex 14
SELECT
    *
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;


--ex 15
SELECT
    LAST_NAME,
    SALARY,
    COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC,COMMISSION_PCT DESC;

SELECT
    LAST_NAME,
    SALARY,
    COMMISSION_PCT
FROM EMPLOYEES
ORDER BY SALARY DESC,COMMISSION_PCT DESC;


--ex 16
SELECT
    LAST_NAME
FROM EMPLOYEES
WHERE upper(LAST_NAME) LIKE '__A%';

--ex 17
SELECT
    LAST_NAME "nume"--,
    --DEPARTMENT_ID,
    --MANAGER_ID
FROM EMPLOYEES
WHERE upper(LAST_NAME) like '%L%L%' AND (DEPARTMENT_ID=50 OR MANAGER_ID=102);


--ex 18
SELECT
    FIRST_NAME || ' ' || LAST_NAME "nume",
    JOB_ID "job",
    SALARY "salariu"
FROM EMPLOYEES
WHERE (JOB_ID like '%REP%' OR JOB_ID like '%CLERK%') AND
      to_char(SALARY) NOT IN (1000,2000,3000);