-----BD laborator 3-----

--ex 1
SELECT
    J.JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE E.DEPARTMENT_ID=30;

--ex 2
SELECT
    E.LAST_NAME "nume",
    D.DEPARTMENT_NAME "departament"
FROM EMPLOYEES E
JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.LAST_NAME LIKE '%a%';


--ex 3
SELECT
    E.LAST_NAME,
    J.JOB_TITLE,
    D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN JOBS J ON  E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE lower(L.CITY)='oxford';


--ex 4
SELECT
    E.EMPLOYEE_ID,
    J.JOB_TITLE,
    SALARY
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY>=3000 OR E.SALARY=(J.MAX_SALARY+J.MIN_SALARY)/2;


--ex 5
SELECT
    D.DEPARTMENT_NAME,
    D.DEPARTMENT_ID,
    E.LAST_NAME,
    J.JOB_TITLE
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE lower(D.DEPARTMENT_NAME) LIKE '%ti%'
GROUP BY D.DEPARTMENT_NAME, D.DEPARTMENT_ID, E.LAST_NAME, J.JOB_TITLE
ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME;


--ex 6
SELECT
    E.EMPLOYEE_ID "ang#",
    E.LAST_NAME ||' '||E.FIRST_NAME "angajat",
    M.EMPLOYEE_ID "mgr#",
    M.LAST_NAME ||' '||M.FIRST_NAME "manager"

FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID=M.EMPLOYEE_ID;


--ex 7
SELECT
    E.LAST_NAME,
    E.HIRE_DATE,
    E2.HIRE_DATE
FROM EMPLOYEES E
JOIN EMPLOYEES E2 ON upper(E2.LAST_NAME)='KING'AND
                     E.HIRE_DATE<E2.HIRE_DATE;


--ex 8
SELECT
    DISTINCT E.LAST_NAME,E.EMPLOYEE_ID,
             D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN EMPLOYEES E2 ON E.DEPARTMENT_ID=E2.DEPARTMENT_ID AND
                        UPPER(E2.FIRST_NAME) LIKE '%T%' AND
                        E.EMPLOYEE_ID <> E2.EMPLOYEE_ID
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--ex 9
SELECT
    E.FIRST_NAME,E.SALARY,
    J.JOB_TITLE,
    L.CITY,C.COUNTRY_NAME
FROM EMPLOYEES E
JOIN EMPLOYEES M ON M.EMPLOYEE_ID=E.MANAGER_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
WHERE M.LAST_NAME='King';

--ex 10
SELECT
    D.DEPARTMENT_NAME
FROM DEPARTMENTS D
WHERE lower(D.DEPARTMENT_NAME) LIKE '%re%'
UNION
SELECT
     D2.DEPARTMENT_NAME
FROM DEPARTMENTS D2
JOIN EMPLOYEES E ON D2.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE upper(E.JOB_ID)='SA_REP';

--ex 11
SELECT
    D.DEPARTMENT_ID
FROM DEPARTMENTS D
MINUS
SELECT
    distinct E.DEPARTMENT_ID
FROM EMPLOYEES E