---BD Laborator 2--


--ex 1
SELECT
    FIRST_NAME ||' ' ||LAST_NAME || ' castiga ' ||
    SALARY || ' dar doreste ' || 3*SALARY as "Salariu ideal"
FROM EMPLOYEES;

--ex 2
SELECT
    INITCAP(FIRST_NAME),
    UPPER(FIRST_NAME),
    LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'L%'
   OR FIRST_NAME LIKE 'J%'
   OR FIRST_NAME LIKE '__a%';

SELECT
    INITCAP(FIRST_NAME),
    UPPER(FIRST_NAME),
    LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,1,1) IN ('J','M') OR
      SUBSTR(UPPER(FIRST_NAME),3,1) ='A';


--ex 3
SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE trim(lower(FIRST_NAME))='steven';

--ex 4
SELECT
    EMPLOYEE_ID cod,
    LAST_NAME nume,
    LENGTH(LAST_NAME) as lungime_nume,
    INSTR(LOWER(LAST_NAME),'a') poz_a
FROM EMPLOYEES
WHERE LAST_NAME like '%e';


--ex 5
SELECT
    LAST_NAME,FIRST_NAME,
    HIRE_DATE
FROM EMPLOYEES
where mod(trunc(sysdate-HIRE_DATE),7)=0


--ex 6
SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    TO_CHAR(SALARY + SALARY * 15/100,'9999999999.99') "SALARIU NOU",
    ROUND((SALARY + SALARY * 15/100)/100, 2) "NUMAR SUTE"
FROM EMPLOYEES;

--ex 7
SELECT
    LAST_NAME,SALARY,
    FLOOR(SALARY/1000),
    TRIM(LPAD(' ',FLOOR(SALARY/1000)+1,'$'))

FROM EMPLOYEES;

--ex 9
SELECT
    TO_CHAR(SYSDATE+30,'MON-DD-YYYY HH:MI:SS')
FROM DUAL;

--ex 9
SELECT
    ceil(TO_DATE('01-01-' || TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))+1))-SYSDATE),
    SYSDATE
FROM DUAL;

--ex 10
SELECT
    SYSDATE+1/24/2
FROM DUAL;

SELECT
    SYSDATE,
    SYSDATE+1/24/12,
    SYSDATE+5/24/60
FROM DUAL;


--ex 11
SELECT
    FIRST_NAME || LAST_NAME "nume",
    HIRE_DATE,
    NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),'MONDAY') "negociere"

FROM EMPLOYEES;


--ex 12
SELECT
    FIRST_NAME,
    MONTHS_BETWEEN(SYSDATE, HIRE_DATE) AS "NUMAR LUNI"
FROM EMPLOYEES
ORDER BY "NUMAR LUNI" desc;





--ex 13
SELECT
    FIRST_NAME, HIRE_DATE,
    TO_CHAR(HIRE_DATE, 'DAY') AS ZI
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE, 'D');



--ex 15
SELECT
    FIRST_NAME || LAST_NAME "nume",
    NVL(TO_CHAR(COMMISSION_PCT,'0.9999'),'fara comision') "comison"
FROM EMPLOYEES;

--ex 16
SELECT
    FIRST_NAME || LAST_NAME "nume",
    SALARY "salariu",
    NVL(TO_CHAR(COMMISSION_PCT,'0.9999'),'fara comision') "comison"
FROM EMPLOYEES where SALARY+SALARY*NVL(COMMISSION_PCT,0)>=10000;

--ex 17
SELECT
    LAST_NAME,JOB_ID,SALARY,
    CASE
        WHEN JOB_ID='IT_PROG' THEN SALARY+SALARY*0.20
        WHEN JOB_ID='SA_REP' THEN SALARY+SALARY*0.35
        WHEN JOB_ID='SA_MAN' THEN SALARY+SALARY*0.25
        ELSE SALARY
    END "marire"
FROM EMPLOYEES