--lab 13
--30 mai 2025


-------RECAP SQL------------
----BD SERIE 2 exercitii----


--ex 1
WITH ACTION_PEOPLE AS (
    SELECT
        C.ID_CLIENT as Nume,
        COUNT(DISTINCT M.ID_MOVIE) as Nr_Filme
    FROM CLIENTS C
    LEFT JOIN BOOKINGS B ON C.ID_CLIENT = B.ID_CLIENT
    LEFT JOIN MOVIE_SCREENING_ROOM MSR ON B.ID_SCREENING = MSR.ID_SCREENING
    LEFT JOIN MOVIES M ON MSR.ID_MOVIE = M.ID_MOVIE
    WHERE M.GENRE = 'ACTION'
    GROUP BY C.ID_CLIENT
)
SELECT
    C.NUME,
    DECODE(A.Nr_Filme,NULl,'---',A.Nr_Filme)
FROM CLIENT C
LEFT JOIN ACTION_PEOPLE A ON C.ID_CLIENT = A.Nume;



--ex 2
SELECT
    COUNT(DISTINCT C.ID_CLIENT) as Clienti_Vip
FROM CLIENT C
JOIN BOOKINGS B ON C.ID_CLIENT=B.ID_CLIENT
JOIN MOVIE_SCREENING_ROOM MSR ON B.ID_SCREENING=MSR.ID_SCREENING
JOIN SCREENING_ROOMS R ON MSR.ID_ROOM = R.ID_ROOM
WHERE R.TYPE='VIP';




--ex 3
SELECT
    M.NAME,
    SUM(MSR.TICKET_PRICE*B.NUMBER_TICKETS)
FROM BOOKINGS B
JOIN MOVIE_SCREENING_ROOM MSR ON B.ID_SCREENING = MSR.ID_SCREENING
JOIN MOVIES M ON MSR.ID_MOVIE = M.ID_MOVIE
WHERE MSR.SCREENING_DATE >= DATE '2024-04-01' AND MSR.SCREENING_DATE <= DATE '2024-04-22'
GROUP BY M.NAME













